---
version: 2
controller: {}
workers:
- type: router
  options:
    pythonpath:
    - ".."
  realms:
  - name: realm1
    roles:
    - name: anonymous
      permissions:
      - uri: "*"
        allow:
          call: true
          register: true
          publish: true
          subscribe: true
  transports:

  - type: web
    endpoint:
      type: tcp
      port: "$PORT"  # Use env var for heroku deployments
    paths:
      ws:
        type: websocket
        serializers:
        - json
        